### ISSUE TITLE
Question: What would it take to use ExoPlayer instead of MediaPlayer here?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [SCratORS/ImageWallpaperSC#9]
I'm surprised to see it works so well with MediaPlayer.
Wouldn't using ExoPlayer be better, as it supports more functionality?
Is it hard to do it?

**Comment by SCratORS** [comment]
This will require the implementation of the ExoPlayer framework, which will greatly increase the size of the output file. It is also possible that this will require the application to grant permissions for ExoPlayer functions to work. All of this is not included in the concept of my application.

**Comment by AndroidDeveloperLB** [comment]
ExoPlayer  doesn't need permissions.

And many apps use ExoPlayer .

ExoPlayer has an extension for AV1 decoding, which works back to Android KitKat (SDK 19): https://github.com/androidx/media/tree/release/libraries/decoder_av1

So it has advantages...

Say, is this repository still maintained? If not, would you please consider changing the license to be more permissive? Or at least to the basic parts of it?

There aren't many open sourced repositories that show how to show images&videos on live wallpapers so well, using OpenGL.

**Comment by SCratORS** [comment]
Updates to this repository will be made only in case of critical code changes or bug fixes. Currently, I am completely satisfied with the operation of the application. It is worth noting that I developed this application on my own and for my own purposes. There was no commercial purpose. Just for myself. Therefore, I decided that publishing its source code under the GPL-3 license would be quite justified, because I would like my work not to be used for commercial gain without publishing the source codes. I am very glad that my code has helped you in understanding how Live Wallpapers work with OpenGL.

And once again, I will formulate the main idea of this application - Only standard system functions. Therefore, only the system media player. Most likely, this is why it was easy for you to understand how it works.

**Comment by AndroidDeveloperLB** [comment]
You say it would be much harder to understand with ExoPlayer in the mix? Maybe.

Can you please consider having the most basic repository for the live wallpaper with a more permissive license?
Meaning it will show image/video, with horizontal scrolling, and that's it. 
You've added a lot of features to the app, and I only wanted to see the very basics of it...

I believe that the smaller an example is, the easier it is to learn from it.
I've seen Google often offer very fancy examples, but when I looked at their code it became unclear what's going on, as their code is so large... 

If you want ideas of the app, I think you can add scale-type (like what ImageView has). Won't be so useful though, as users usually want the image to fill all spaces...
You can also make it resume the playback of the video instead of starting from the beginning, each time you return to the wallpaper.
I think this should be easy.

**Comment by AndroidDeveloperLB** [comment]
@SCratORS Why close as completed? It uses Exoplayer now?

**Comment by SCratORS** [comment]
I don't see any connection between the request to make a "simple repository" and the problems of the application.

Also, I have no desire to add work with libraries of external video players to the application.

If you want to add something to the functionality of the application. Please do a PR. I'll look into it.

**Comment by AndroidDeveloperLB** [comment]
1. Exoplayer can give you more potential of more features, no?
2. Is it possible to make the video pause instead of restart?
3. Having a simple repository is a good thing to be able to fork and create other apps, that don't need all the extra features you've added here. Perhaps you could even make the current one better on the way, as you will find things you could improve or clean.

**Comment by SCratORS** [comment]
1. Maybe, but I don't need it. My idea is to use only regular features, without involving external libraries.
2. No. The video is looped. When the application is "invisible", the video is paused to save resources.
3. Those who need it can create what they need on their own. The Internet is full of examples of how to make wallpapers. During the development of your application, you will have questions and maybe you can find answers to them from this repository. If you haven't tried to create an application yourself, even a simple example won't help you.

**Comment by AndroidDeveloperLB** [comment]
1. too bad. Do you think it will be hard? 
2. I don't understand . You are saying it's impossible to pause instead of a restart ? I already know about it looping. I asked about changing the behavior so that instead of start from beginning after going back to the live wallpaper, it will just resume from being paused. 
If you don't understand, imagine you are watching some YouTube video, and you get a phone call and you answer it. When you get back to the video, instead of resuming from where you've left it, the video would restart from the beginning...
3. I see. It's just that this specific topic is lacking a lot (meaning not much material to read at all, sadly), of a live wallpaper and being able to draw on it from special sources, and not just a Canvas. Even with Canvas there isn't much explanation. Not to mention tutorials and samples...
Can you tell where you've learned it all from?

**Comment by SCratORS** [comment]
1. It's not that it's difficult or not. I just don't want to do it. I want the application to work with system components without using external libraries.
2. It is paused, and after returning it continues from the place where it stopped. It's very strange that you have it starting from the beginning.
3. At first, I was looking for information in general, like a live wallpaper.
And after reading the information I found, I managed to just make a "simple" application.
Then, having figured it out, I was looking for how to screw opengl to this.

**Comment by AndroidDeveloperLB** [comment]
1. ok

2. No, it's not pause&resume. It's pause&restart. If you intended it to pause&resume, it's a bug because that's not how it works. I can show you a video if you wish. 
The steps are easy: set a video that you know how it looks like in beginning. Watch it a bit in the live wallpaper. Turn off screen to reach lock screen (important to have a lock screen set). Turn on screen. That's it.
Here, a video on Pixel 6 with Android 15 (also happened on Android 14), using the APK of the repository, and the video from here:
http://docs.evostream.com/sample_content/assets/bun33s.mp4

[1.zip](https://github.com/user-attachments/files/17533594/1.zip)

For some reason, I don't see it on the emulator with Android 14. Weird.

If you want, I can create a new report.

3. Sadly for OpenGL, my experiene&knowledge of it was lost a long time ago, as I used the first versions, but later it changed to 2.0 and 3.0, and both of them are completely different. Adding Android to the mix makes it hard for me to see how things work.

**Comment by SCratORS** [comment]
2. I put the video on my Pixel7a, android 15.
When the screen is locked, the video is paused, and playback continues when turned on. 
I do not observe the problem that you showed in the video.

**Comment by AndroidDeveloperLB** [comment]
I've shown on the video, that after turn off&on, the text that appears in the beginning appears again and again, meaning the one with the long text of "The peach open movie project presents".

At time 0:05 you can see the text of the beginnig:

![image](https://github.com/user-attachments/assets/54b66635-013d-4d64-9d37-140ff9481f63)

Then on 0:06, you can see the text is gone as the there is new content after it:

![image](https://github.com/user-attachments/assets/95b40f98-8cf8-4aec-ae90-168da27feb72)

But then after a few seconds later, when I turn off&on the display, look at 0:09, as the text in the beginning appeared yet again:
 
![image](https://github.com/user-attachments/assets/d9cfd9b2-fb88-4d90-aaad-b1a9fef54bc8)

So, that's not resuming. That's restarting.

If I turn on sound, you can notice it even better.
Here, watch with sound and listen as the music doesn't continue from where it was supposed to pause, and in fact you can hear that the music restarted at the moment I turned off the display :

[2.zip](https://github.com/user-attachments/files/17534148/2.zip)

I can show you this with a different video, if you wish. Here's an easier one to notice, as it starts with a clock on 0:00:
https://pixabay.com/videos/clock-time-minutes-green-screen-149068/

Here, watch:

[3.zip](https://github.com/user-attachments/files/17534168/3.zip)

**Comment by SCratORS** [comment]
I understand what's going on in the video. I see that a restart is taking place. 
I can't reproduce this behavior on my real smartphone. - everything is working correctly.

**Comment by AndroidDeveloperLB** [comment]
I know what happened....
I have double-click to turn off the display as part of the Nova launcher settings.
And, the live wallpaper has double-click change the wallpaper, even when I choose a single wallpaper.
This explains why I can't see it on emulator.

So, the bug is that it tries to change wallpaper when there is only one and instead restarts the current one, and that this feature is turned on without me turning it.

I have found another bug though, which I wrote you somewhere else:
The scrolling is a buggy (when choosing "scroll effect"), as it uses speed instead of precise number based on scroll X location.
Can you please add this behavior instead, when choosing "scroll" ? 
Watch what I'm talking about:
[4.zip](https://github.com/user-attachments/files/17534512/4.zip)

I stay on the same page on the edge of the launcher on the right, just playing with overscrolling. The content changes to either have the clock shown or not when becoming idle. Sometimes even shows much more of the clock for some reason.
It should use onOffsetsChanged only , and avoid speed. When I reach the edge, it should stay on the edge.

**Comment by SCratORS** [comment]
Swipe is a bit of a specific thing. There is a function in the settings - "swipe response" It is needed specifically to change behavior.
For example. If the launcher is able to transmit a Swipe event, then you can select this setting in the application, and then swipe control will be used from the launcher. In this case, the screen will not shift when the edge is reached.
But if there is no such event in the launcher, then there will be no reaction to the swap at all, for this there is another setting that makes the scroll offset.

**Comment by AndroidDeveloperLB** [comment]
As you can see on the video, I have chosen scroll. Not swipe. 
Both of them don't work properly.
I expect that when I reach the edge, it will reach it on the live wallpaper too, always. 
When reaching 100% to the right, the scrolling should reach 100% on the video.

This can be reproduced even on emulator. I've seen it in the past. 
Was wondering why speed is added even for scrolling. Should be using only exact position. 

Or perhaps the speed is to make it move nicely, but it has a bug so it ignores some events or that some events ruin the others.

The launcher isn't the issue. Printing to logs I can see it myself.

Can you please tell me how I should change it to fix this behavior? Or how I should change it to use without speed at all? Pretty sure it should be smooth even without speed.

**Comment by SCratORS** [comment]
The "movement" registers the movement of the finger on the screen and, depending on the speed of movement of the finger on the screen, receives an acceleration of movement.  In this mode, there is no concept of a screen edge. There is a finger movement - there is acceleration.
In the "Launcher Control" mode, the launcher transmits motion acceleration to the application, in this mode, when the end of the screen is reached, the launcher does not transmit motion and it should work as you expect. But it's worth noting that very few launchers transmit this data. If the swipes do not work in this mode, then the launcher used does not transmit this data.

**Comment by AndroidDeveloperLB** [comment]
@SCratORS That's incorrect. There is no callback of speed/acceleration.
There is a callback of "The launcher is now at X,Y of scrolling right now".
The app changes it to be of speed that degrades (probably to have a smooth transition till it reaches the point), and something is wrong in this behavior.
Look:

https://github.com/SCratORS/ImageWallpaperSC/blob/master/java/com/scrat/imagewallpapersc/ImageWallpaperSCService.java#L170
https://github.com/SCratORS/ImageWallpaperSC/blob/master/java/com/scrat/imagewallpapersc/ImageWallpaperSCRender.java#L738
https://github.com/SCratORS/ImageWallpaperSC/blob/master/java/com/scrat/imagewallpapersc/ImageWallpaperSCRender.java#L566

You can see it uses setMotionSpeed instead of just reaching the new location right away, and there is no alternative there to a go-to behavior. 

It's not because of the launcher. It's because of the app. It doesn't use the onOffsetsChanged callback as it should:
https://developer.android.com/reference/android/service/wallpaper/WallpaperService.Engine#onOffsetsChanged(float,%20float,%20float,%20float,%20int,%20int)
https://developer.android.com/reference/android/app/WallpaperManager#setWallpaperOffsets(android.os.IBinder,%20float,%20float)

" The X and Y offsets are floating point numbers ranging from 0 to 1, representing where the wallpaper should be positioned within the screen space"

For horizontal scrolling, the "xOffset" of onOffsetsChanged tells you what is the state of the scrolling in X coordinate.

If you think it's because of the launcher, show me one launcher that you think works as it should, that I can install and I will show you the issue exists there too.
But according to my test, of putting logs for this callback, it works fine as it should, so your claim isn't based on testing the launcher with the live wallpaper. 
I can show you a video proving it, too.

BTW, Nova launcher is very popular, and this issue doesn't exist on it when using other live wallpapers.

**Comment by SCratORS** [comment]
Google Pixel Launcher
HTC Sense (BlinkFeed)
Nova Launcher

In order for the Launcher-controlled movement to work, do not forget to add additional desktops, between which a swipe will work.

I checked the work with Nova Launcher - it works correctly.

**Comment by AndroidDeveloperLB** [comment]
@SCratORS The video I've shown is of Nova launcher. Have you used the input video I've offered, of the clock?
About the other launchers, I can't find BlinkFeed and don't think I can install it easily on my Pixel 6. 
As for Pixel launcher, same issue occurs there as on Nova launcher.

I have additional desktops, and what I've shown is when reaching the edge (most right) . 

It doesn't work correctly at all. I've shown you on video. Here, tested on Pixel launcher too, with just 2 pages on the launcher:

[5.zip](https://github.com/user-attachments/files/17577774/5.zip)

Sometimes it shows the tiny portion of the clock. Sometimes it shows nothing. Sometimes it shows a large portion of it.

Here are screenshots of the possible outcomes of scrolling to the right-most page on the launcher, and you can see that I don't scroll as the icons aren't stretched:

![image](https://github.com/user-attachments/assets/073ab365-4415-4a04-8985-b69dc235ef2b)

![image](https://github.com/user-attachments/assets/d2ba4af2-31c6-460f-b6dd-1fe9509ca4db)

![image](https://github.com/user-attachments/assets/dbc7069a-c520-4d09-94ef-c44439045f16)

Please fix this, and also use the callback without motion at all, going directly to the position it's supposed to go.
I can also provide you with a video that includes Logcat, to show that any launcher you want to test works fine, and the live wallpaper just doesn't handle the new callback properly, reaching to the edge.
